import tkinter as tk
from textblob import TextBlob
root=tk.Tk()
root.title('SPELL CHECKER')
canvas1=tk.Canvas(root,width=500,height=500,bg='pink')
canvas1.pack()
label1=tk.Label(root,text='SPELL CHECKER')
label1.config(font=('helvetic',15))
canvas1.create_window(250,90,window=label1)
entry1=tk.Entry(root)
canvas1.create_window(250,200,window=entry1)
def clicked():
    a=(entry1.get()).lower()
    print("Original text:",str(a))
    b=TextBlob(a)
    print("Corrected text:",str(b.correct()))
    label2=tk.Label(root,text='corrected word')
    label2.config(font=('helvetic',15))
    canvas1.create_window(250,400,window=label2)
    label3=tk.Label(root,text=str(b.correct()))
    canvas1.create_window(250,450,window=label3)
button1=tk.Button(text='Check it',command=clicked,bg='black',fg='white')
canvas1.create_window(250,300,window=button1)
root.mainloop()